// <auto-generated />
namespace Irving.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using System.Diagnostics.CodeAnalysis;

    [ExcludeFromCodeCoverage]
    public sealed partial class AddedNameToAsset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedNameToAsset));
        
        string IMigrationMetadata.Id
        {
            get { return "201209141316141_AddedNameToAsset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
